### ISSUE TITLE
Error: No WebSocketChannel found in the storage description resource.

### ISSUE THREAD

**Issue by j-steinbach** [SolidLabResearch/Solid-Agent#8] opened 2023-06-22 13:49 UTC
I am trying to get the UCP configuration working based on the [guide](https://github.com/SolidLabResearch/Solid-Agent/tree/main/documentation/ucp), but it fails on ` npx ts-node indexUCP.ts`.

```cli
 ↳ npx ts-node indexUCP.ts
oidc-provider WARNING: Unsupported Node.js runtime version. Use ^12.19.0, ^14.15.0, or ^16.13.0
token expires in: 600 seconds.
Account (http://localhost:3123/solid/profile/card#me) created and logged in true
/home/jst/Projects/KNoWS/SHARCS/Solid-Agent/node_modules/solid-notification-client/dist/NotificationUtil.js:33
            op = body.call(thisArg, _);
                      ^
Error: No WebSocketChannel found in the storage description resource.
    at /home/jst/Projects/KNoWS/SHARCS/Solid-Agent/node_modules/solid-notification-client/dist/NotificationUtil.js:108:31
    at step (/home/jst/Projects/KNoWS/SHARCS/Solid-Agent/node_modules/solid-notification-client/dist/NotificationUtil.js:33:23)
    at Object.next (/home/jst/Projects/KNoWS/SHARCS/Solid-Agent/node_modules/solid-notification-client/dist/NotificationUtil.js:14:53)
    at fulfilled (/home/jst/Projects/KNoWS/SHARCS/Solid-Agent/node_modules/solid-notification-client/dist/NotificationUtil.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Even though the above fails with an error, I still am able to exectute `UcpSendPolicy.ts`

```cli
 ↳ npx ts-node UcpSendPolicy.ts
2023-06-22T13:46:56.064Z Duration policy: https://woutslabbinck.solidcommunity.net/profile/card#me now has access to http://localhost:3000/ldes for PT30S
```

**Comment by woutslabbinck** [comment] 2023-06-22 14:51
It seems like you do not have a Solid server running with the [Solid Notifications Protocol](https://solid.github.io/notifications/protocol)  (more specifically WebSocketChannel2023) on port 3000.

Therefore, the DemoUCPAgent will never be notified when you send a policy to the policy container.

Have you tried setting up a CSS within the directory with following command `npx community-solid-server -c memory-no-setup.json`?

This  [memory config](https://github.com/SolidLabResearch/Solid-Agent/blob/94a01e25c2e3a365ad5dd141bfa50852db0d96b0/memory-no-setup.json#L10) sure has the required notification protocol activated with CSS v6.0.0

**Comment by j-steinbach** [comment] 2023-06-28 12:47
Not sure what I do wrong. 

1. Run `npx community-solid-server -c memory-no-setup.json` to start the server
2. Run `npx ts-node indexUCP.ts` 
3. Get the above-mentioned error
4. (Run ` npx ts-node UcpSendPolicy.ts` and get reported that `2023-06-28T12:46:50.153Z Duration policy: https://woutslabbinck.solidcommunity.net/profile/card#me now has access to http://localhost:3000/ldes for PT30S`

**Comment by woutslabbinck** [comment] 2023-07-10 08:43
After an offline discussion, it suddenly works now for @j-steinbach.
We'll re-open and further investigate if the problem appears again as currently we cannot reproduce it again.

**Comment by woutslabbinck** [comment] 2023-08-03 15:01
When running CSS v6.0.1, I got the same error. The reason for failure was a difference in the <solid-base-uri>.well-known/solid contents.

v6.0.0. content:
```ttl
<http://localhost:3000/.well-known/solid> rdf:type pim:Storage ;
  notify:subscription <http://localhost:3000/.notifications/WebHookChannel2023/> ,
                                    <http://localhost:3000/.notifications/WebSocketChannel2023/> .
```
v6.0.1 content:
```ttl
<http://localhost:3000/> rdf:type pim:Storage ;
  notify:subscription <http://localhost:3000/.notifications/WebHookChannel2023/> ,
                                    <http://localhost:3000/.notifications/WebSocketChannel2023/> .
```

And in the [Solid Notification Client](https://www.npmjs.com/package/solid-notification-client), a [query](https://github.com/woutslabbinck/Solid-Notification/blob/019b4a7e0da68470476f2a1e6cebcc7ba73786aa/src/NotificationUtil.ts#L45) was executed on both `notify:subscription` and the storage description URL.

A fix that just queries for the `notify:subscribe` triples will solve this.

**Comment by woutslabbinck** [comment] 2023-08-03 15:17
Fixed by bumping the solid notification client (https://github.com/SolidLabResearch/Solid-Agent/commit/ae327826cb5af12ab6637c34fd6f95dc161df485)

**Closed by woutslabbinck** 2023-08-03 15:17 UTC
